import { type ShopBrief } from "../brief.js";

export function generateThemeCss(brief: ShopBrief): string {
  return `/**
 * Theme: ${brief.storeName}
 * Generated by create-cartwright
 */
:root {
  --color-accent: ${brief.palette.primary};
  --color-cream: ${brief.palette.background};
  --color-sand: ${brief.palette.background}; /* Fallback until more colors requested */
  --color-ink: #1a1a1a;
  --color-muted: #726d62;
  --color-success: ${brief.palette.primary};
}
`;
}

export function generatePromptModule(brief: ShopBrief): string {
  return `/**
 * AI System Prompt: ${brief.storeName}
 * Generated by create-cartwright
 */
export const systemPrompt = \`
Du er AI-assistent for ${brief.storeName}.
Tagline: ${brief.tagline}
Vi sælger: ${brief.sells}
Målgruppe: ${brief.audience}
Tone of voice: ${brief.tone}
\`;
`;
}

export function generateSeedData(brief: ShopBrief): string {
  return `/**
 * Seed data: ${brief.storeName}
 * Generated by create-cartwright
 */
export const seedData = {
  categories: ${JSON.stringify(brief.categories, null, 2)},
  products: ${JSON.stringify(brief.products, null, 2)},
  pages: []
};
`;
}
